"""Render findings as JSON or Markdown."""
from __future__ import annotations

import json
from .models import Finding

_SEV_EMOJI = {"HIGH": "🔴", "MEDIUM": "🟠", "LOW": "🟡", "INFO": "⚪"}


def to_json(findings: list[Finding], target: str) -> str:
    counts: dict[str, int] = {}
    for f in findings:
        counts[f.severity] = counts.get(f.severity, 0) + 1
    return json.dumps(
        {
            "target": target,
            "summary": {"total": len(findings), "by_severity": counts},
            "findings": [f.as_dict() for f in findings],
        },
        indent=2,
    )


def to_markdown(findings: list[Finding], target: str) -> str:
    counts: dict[str, int] = {}
    for f in findings:
        counts[f.severity] = counts.get(f.severity, 0) + 1
    lines = [f"# intentscope report — `{target}`", ""]
    if not findings:
        lines.append("No deep-link / exported-component issues found. ✅")
        return "\n".join(lines) + "\n"
    summary = " · ".join(
        f"{_SEV_EMOJI.get(s, '')} {counts[s]} {s}"
        for s in ("HIGH", "MEDIUM", "LOW", "INFO") if s in counts
    )
    lines += [f"**{len(findings)} finding(s):** {summary}", ""]
    for f in findings:
        lines += [
            f"## {_SEV_EMOJI.get(f.severity, '')} {f.severity} — {f.title} (`{f.rule_id}`)",
            f"- **Component:** `{f.component}`",
            f"- **Detail:** {f.detail}",
            f"- **Fix:** {f.recommendation}",
            "",
        ]
    return "\n".join(lines) + "\n"


_SARIF_LEVEL = {"HIGH": "error", "MEDIUM": "warning", "LOW": "warning", "INFO": "note"}


def to_sarif(findings: list[Finding], target: str) -> str:
    rules_seen: dict[str, dict] = {}
    results = []
    for f in findings:
        rules_seen.setdefault(f.rule_id, {
            "id": f.rule_id,
            "name": f.title,
            "shortDescription": {"text": f.title},
            "defaultConfiguration": {"level": _SARIF_LEVEL.get(f.severity, "note")},
        })
        results.append({
            "ruleId": f.rule_id,
            "level": _SARIF_LEVEL.get(f.severity, "note"),
            "message": {"text": f"{f.component}: {f.detail} Fix: {f.recommendation}"},
            "properties": {"security-severity": {
                "HIGH": "8.5", "MEDIUM": "5.5", "LOW": "3.0", "INFO": "0.0"}.get(f.severity, "0.0")},
            "locations": [{"physicalLocation": {
                "artifactLocation": {"uri": target},
                "logicalLocations": [{"fullyQualifiedName": f.component}],
            }}],
        })
    return json.dumps({
        "version": "2.1.0",
        "$schema": "https://json.schemastore.org/sarif-2.1.0.json",
        "runs": [{
            "tool": {"driver": {
                "name": "intentscope",
                "informationUri": "https://github.com/matthew6s/intentscope",
                "rules": list(rules_seen.values()),
            }},
            "results": results,
        }],
    }, indent=2)


def to_html(findings: list[Finding], target: str) -> str:
    counts: dict[str, int] = {}
    for f in findings:
        counts[f.severity] = counts.get(f.severity, 0) + 1
    color = {"HIGH": "#c0392b", "MEDIUM": "#e67e22", "LOW": "#f1c40f", "INFO": "#95a5a6"}
    rows = "".join(
        f'<tr><td><span style="background:{color.get(f.severity)};color:#fff;'
        f'padding:2px 8px;border-radius:4px;font-size:12px">{f.severity}</span></td>'
        f'<td><code>{f.rule_id}</code></td><td><code>{f.component}</code></td>'
        f'<td><b>{f.title}</b><br>{f.detail}<br><i>Fix:</i> {f.recommendation}</td></tr>'
        for f in findings
    )
    summary = " · ".join(f"{counts[s]} {s}" for s in ("HIGH", "MEDIUM", "LOW", "INFO") if s in counts)
    return f"""<!doctype html><html><head><meta charset="utf-8">
<title>intentscope — {target}</title>
<style>body{{font:14px system-ui,sans-serif;margin:2rem;color:#1a1a1a}}
h1{{font-size:20px}}table{{border-collapse:collapse;width:100%}}
td,th{{border:1px solid #ddd;padding:8px;vertical-align:top;text-align:left}}
th{{background:#1f2a37;color:#fff}}code{{background:#f2f2f2;padding:1px 4px;border-radius:3px}}</style>
</head><body>
<h1>intentscope report — <code>{target}</code></h1>
<p><b>{len(findings)} finding(s):</b> {summary or 'none ✅'}</p>
<table><tr><th>Severity</th><th>Rule</th><th>Component</th><th>Detail</th></tr>{rows}</table>
<p style="color:#888;margin-top:2rem">Generated by intentscope · github.com/matthew6s/intentscope</p>
</body></html>
"""
